### ISSUE TITLE
Sort newer versions at the top?

### ISSUE THREAD

**Issue by chriskuehl** [chriskuehl/dumb-pypi#11]
I usually want the latest version, maybe we should reverse the sort order? That would save a lot of scrolling when there are many versions.

**Comment by chriskuehl** [comment]
(talking about this view: https://chriskuehl.github.io/dumb-pypi/test-repo/simple/django-admin-shortcuts/)

**Comment by asottile** [comment]
This sounds like a good idea to me (pip probably doesn't care either because public pypi is terribly unsorted)
