### ISSUE TITLE
proposal: include helper script to generate packages.json

### ISSUE THREAD

**Issue by FelixSchwarz** [chriskuehl/dumb-pypi#137]
I understand that dumb-pypi by design does not require access to actual packages. However sometimes there are just a few packages so all of them might be available locally. At the same time I also need the hash (either md5 or sha, does not matter) being present in the generated HTML (because these are required for `conda-lock` files).

Writing such a Python script is not a big deal but yet another script in the repo which might be actually shared functionality. Would you mind including such a script as part pf dumb-pypi?

**Comment by asottile** [comment]
everyone is going to have different needs for what they want to put into dumb-pypi and how they want to source it, etc. -- dumb-pypi intentionally is agnostic to how you store your packages and how you host the pypi server.

there's no way we could make something universally useful and so we have not added such a file to the repository (beyond [the test helper file which generates the fake one](https://github.com/chriskuehl/dumb-pypi/blob/master/testing/package-list-to-fake-json)) -- and I don't think it would be fun to try and maintain such a thing

**Comment by FelixSchwarz** [comment]
I thought an optional CLI script might be acceptable but I can see the value in really keeping the feature set minimal. Thank you for the software btw.
