### ISSUE TITLE
Push token expired?

### ISSUE THREAD

**Issue by asottile** [chriskuehl/dumb-pypi#18]
travis is having issues pushing to gh-pages, I tried running it locally [and it succeeded](https://github.com/chriskuehl/dumb-pypi/commit/1bcfa45ee636559bfa6e635fd3dda2dd067373a8)

**Comment by chriskuehl** [comment]
Somehow the @chriskuehl-travis user's API key disappeared entirely from GitHub...

Generated a new one and updated the Travis config, looks like it's working now! https://travis-ci.org/chriskuehl/dumb-pypi/builds/308585500

**Comment by asottile** [comment]
Nice to see the more brief output too! (thanks to https://github.com/anthonywritescode/markdown-to-presentation/issues/3)
