### ISSUE TITLE
Add link to Docker images

### ISSUE THREAD

**Issue by lorddaedra** [chriskuehl/dumb-pypi#53]
Hello, @chriskuehl !

Thanks for your work. 

I've just created container images with your package. It can be useful too for some environments.

https://github.com/backupner/dumb-pypi-image

**Comment by lorddaedra** [comment]
List of available image tags: https://hub.docker.com/r/backupner/dumb-pypi/tags

**Comment by asottile** [comment]
https://github.com/chriskuehl/dumb-pypi/issues/85#issuecomment-1152922996
