### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by modem7** [chriskuehl/dumb-pypi#85]
As #53 hasn't been updated for two years, I've built my own version with a couple of improvements and added documentation.

https://github.com/modem7/docker-dumb-pypi

https://hub.docker.com/r/modem7/dumb-pypi

This is currently being used in production to great effect under https://github.com/modem7/PyPI ([build_pypi_wheels.sh](https://github.com/modem7/PyPI/blob/5cfd7596c402647bd4371efa6f85a4f2a0260a56/build_pypi_wheels.sh#L27-L29) and [build_borg_wheels.sh]( https://github.com/modem7/PyPI/blob/5cfd7596c402647bd4371efa6f85a4f2a0260a56/build_borg_wheels.sh#L18-L20))

If this is useful, it may be beneficial to add it to the documentation, and if it isn't, please feel free to close this issue. 

Thanks!

**Comment by asottile** [comment]
I don't really think an image that just runs `pip install dumb-pypi` is all that useful -- anyone can replicate that in the flavor they care about
